const user = localStorage.getItem("user");

$(document).ready(function () {
    let settings = {
        "async": true,
        "crossDomain": true,
        "url": "https://covidcurious-a7f1.restdb.io/rest/accounts",
        "method": "GET",
        "headers": {
            "content-type": "application/json",
            "x-apikey": "620e5be234fd621565858738",
            "cache-control": "no-cache"
        }
    }

    $("#btn-submit").on("click", function (e) {
        // to not reload the page when submit button is clicked
        e.preventDefault();

        // to run ajax for database
        $.ajax(settings).done(function (response) {
            response.map(account => {
                if (account.Email === $("#email") && account.Password === $("#password")) {
                    // store id generated by the database for the account
                    localStorage.setItem("user", account._id);
                    // redirect back to home page
                    window.location.assign("index.html");
                }
                else{
                    var errorpopup = "Could not find account details"
                    errorpopup.css("red")
                }
            });
        });
    });
});
